#!/bin/bash

installAndroidTools() {
    yes | pkg install android-tools
}

installTermuxApi() {
    yes | pkg install termux-api
}

checkAndInstallPackages() {
    androidToolsInstalled=1
    termuxApiInstalled=1

    if ! pkg files android-tools > /dev/null 2>&1; then
        installAndroidTools
        androidToolsInstalled=0
    fi

    if ! pkg files termux-api > /dev/null 2>&1; then
        installTermuxApi
        termuxApiInstalled=0
    fi

    if [ $androidToolsInstalled -eq 1 ] && [ $termuxApiInstalled -eq 1 ]; then
        return 0 
    else
        return 1
    fi
}

while true; do
    checkAndInstallPackages
    if [ $? -eq 0 ]; then
        break 
    fi
done

while true; do
    if [ -f "$PREFIX/bin/adb" ] && [ -f "$PREFIX/bin/fastboot" ]; then
        mv "$PREFIX/bin/adb" "$PREFIX/bin/-adb" &&
        mv "$PREFIX/bin/fastboot" "$PREFIX/bin/-fastboot" &&
        break 
    fi
    yes | pkg reinstall android-tools
done

while true; do
    curl -s "https://raw.githubusercontent.com/offici5l/termux-adb-fastboot/atest/adb" -o "$PREFIX/bin/adb"
    if [ $? -eq 0 ]; then
        break
    fi
done

while true; do
    curl -s "https://raw.githubusercontent.com/offici5l/termux-adb-fastboot/atest/fastboot" -o "$PREFIX/bin/fastboot"
    if [ $? -eq 0 ]; then
        break
    fi
done

chmod +x "$PREFIX/bin/adb"
chmod +x "$PREFIX/bin/fastboot"

printf "\n\e[1;32m\nadb\e[0m and \e[1;32mfastboot\e[0m ready to use.\n\n"

exit 0